### ISSUE TITLE
Create a terrain tile manager system.

### ISSUE THREAD

**Issue by rsaz** [rsaz/mankind#11]
Player will spawn with the same terrain size
Terrains can be bought and sell
Players can expand their terrains and buy other properties

**Comment by igorfel** [comment]
Created a new branch (7ed3412) to work on this feature.

- Players are already being spawned on its own random terrain cell but with no visualisation yet.

**Comment by rsaz** [comment]
Hi @igorfel thanks for your effort. You are assigned to an important and crucial task to the project. 👍 
Please, the ideal situation is to fork the project, clone locally, make your changes and pull request back to the repo where I can evaluate and integrate with the main project. I think this is a good workflow for now.
Having different branches is a little overhead that I wouldn't like to have at this stage. But thanks for the initiative. Keep the good work

**Comment by igorfel** [comment]
@rsaz no problem, i'll do that just now

**Comment by rsaz** [comment]
Thanks @igorfel , you are great. Keep moving forward with your issue, cause he plays an important and crucial part to the project. :)
