### ISSUE TITLE
Create readme with contribution guide

### ISSUE THREAD

**Issue by AndersonMarquess** [rsaz/mankind#2]
Create a readme with the main guide to new contributors. 

- Language
- Establish folder hierarchy
- Name convention
- Rules for third party assets
- License

[Doc for reference:](https://docs.google.com/document/d/1PwBF4yQl69RxvVHZ2m2iiy5pYjd9QO-VcuXWDjB7QwA/edit#)

**Comment by wilgnne** [comment]
It would be nice to create this in a `CONTRIBUTING.md`

**Comment by wilgnne** [comment]
So we can keep in the README just an overview of the project

**Comment by AndersonMarquess** [comment]
When your contribution is accepted just add the reference in the readme.

**Comment by rsaz** [comment]
> It would be nice to create this in a `CONTRIBUTING.md`

I will be merging this doc into the project, but before doing that I need to see some of the content you want to add in there. Give some example! 👍

**Comment by rsaz** [comment]
Guidelines revamped. Thank your for your contribution.
